### ISSUE TITLE
Add more KSP launch options

### ISSUE THREAD

**Issue by apemanzilla** [oharaandrew314/TinkerTime#177]
Eg: 
-single-instance - only allow one instance of KSP at a given time
-force-opengl - Windows only, helps significantly with memory usage
-adapter *x* - run KSP on non-primary monitor
-nolog - don't create logs files

If these are added, it may be a good idea to put them (and the border less window option) in a new config window seperate from the main one.

**Comment by oharaandrew314** [comment]
When this is implemented, should also move KSP borderless option to this new window.

**Comment by oharaandrew314** [comment]
I don't see the need to create a window to add all of these launch options.  If a user knows about these options, then they probably know how to use launch arguments.  I think I will instead give the user a text field in the main options window to set their own arguments.
