### ISSUE TITLE
Mac OS X compatibility?

### ISSUE THREAD

**Issue by skunkworker** [oharaandrew314/TinkerTime#179]
I've use tinkertime successfully on my windows machine, but whenever I try to use it on my mac it keeps on saying that the module manager version needs to be updated, which macs cant use. And it also says that a mod is enabled when its not. Is there something that I'm doing wrong here?

**Comment by cgruber** [comment]
I'm on a mac and not seeing this - not sure if I'm using a version that fixes this issue, or whether it's the reporter's machine.

**Comment by oharaandrew314** [comment]
Yes, this is old and unconfirmed.  It is entirely possible that these issues are fixed in a newer version.
