### ISSUE TITLE
Move Progress Bars to Mod List Elements

### ISSUE THREAD

**Issue by oharaandrew314** [oharaandrew314/TinkerTime#184]
Instead of having a general progress bar at the bottom of the app, turn each of the elements of the Mod Listing to be a progress bar. Once a task occurs for that mod, display the progress on the element. When a task is queued, the element should reflect this, too.

**Comment by oharaandrew314** [comment]
@apemanzilla and @cgruber, I've been playing around with moving the progress bars to the mod list.  It ends up being more hacky than anticipated since I need to add a framerate timer to animate the progress bars.

I'm also not sure if I really like it.  Do you guys prefer the old placement of the progress bars?  Or would you like me to keep working on the bars integrated with the mod list?


![untitled](https://cloud.githubusercontent.com/assets/894152/7049240/0db79244-dde6-11e4-8652-c5cf4bd05534.png)

**Comment by apemanzilla** [comment]
I liked the old progress bars better. It looks too squeezed in with them next to the mods.

**Comment by oharaandrew314** [comment]
I could fix that.  I'm just not sure if it's worth putting the time into making a fully-custom ListCellRenderer.

**Comment by apemanzilla** [comment]
Well, to be fair it's actually rather easy to write a basic ListCellRenderer: 
[Basic tutorial](http://www.java2s.com/Tutorial/Java/0240__Swing/AddyourownListCellRenderer.htm)

**Comment by oharaandrew314** [comment]
It's starting to get a bit closer to how I imagined it would be.
![capture](https://cloud.githubusercontent.com/assets/894152/7108312/69992d8a-e150-11e4-84ba-9fb7fe6206db.PNG)

**Comment by cgruber** [comment]
A little spinner - or circular progress bar might be better.  One that just
travels 360 degrees to represent completion.  It'd be way less obtrusive.

**Comment by oharaandrew314** [comment]
@cgruber, if I were just showing indeterminate progress, I would agree with you.  However, this bar also shows longer-running tasks where I show a determinate progress bar.  For example KW Rocketry is quite big, and the user would want to see the actual progress.

I could show a spinner when the progress is indeterminate, and a progress bar otherwise, though.  What do you think of that?

**Comment by cgruber** [comment]
No - I mean it's like a circle which has... hmm... this is hard to
describe.  Let me find a gif... like what you see in this image search.
https://www.google.com/search?q=blah+foo&newwindow=1&safe=off&es_sm=91&source=lnms&tbm=isch&sa=X&ei=zRUrVaPwHZDxoASAjoGYDQ&ved=0CAcQ_AUoAQ&biw=1125&bih=786#newwindow=1&safe=off&tbm=isch&q=circular+progress+bar+gif

When the bar closes the full 360, you're done.  So it's definite progress,
not indefinite motion.

**Comment by oharaandrew314** [comment]
@cgruber, I missed something in your last post, so I rewrote my previous comment.

**Comment by oharaandrew314** [comment]
Oh, a percentage indicator along with the graphic would show the precision I want for larger downloads.
