### ISSUE TITLE
Make the Options Window Prettier

### ISSUE THREAD

**Issue by oharaandrew314** [oharaandrew314/TinkerTime#191]
The Options Window is ugly, and the options change position randomly due to a set somewhere.

Make it prettier, and make the order of the options consistent.

Also make the "X" dialog button act as a cancel.

**Comment by apemanzilla** [comment]
Why not use a LinkedHashSet as opposed to a Collection for the option objects? LinkedHashSets retain the order that they were added in when iterated through, which should end up with the same order every time assuming it's hardcoded.

**Comment by oharaandrew314** [comment]
That's the plan.

**Comment by oharaandrew314** [comment]
Much better.

![capture](https://cloud.githubusercontent.com/assets/894152/7289372/31458952-e93d-11e4-98d9-01094a3e405f.PNG)

**Comment by apemanzilla** [comment]
Not bad! If you could make the left cells bold then it would be almost perfect IMO.

**Comment by oharaandrew314** [comment]
That's a good idea.

**Comment by apemanzilla** [comment]
Also, removing the cell borders might make it look a bit more "natural."

**Comment by oharaandrew314** [comment]
I'll see how that looks.
