### ISSUE TITLE
Hidden fields in the config window still expand it vertically

### ISSUE THREAD

**Issue by apemanzilla** [oharaandrew314/TinkerTime#209]
Hidden fields still expand the option window vertically despite not showing:
![Image](http://i.imgur.com/qHVVIcz.png)

**Comment by oharaandrew314** [comment]
Interesting!

**Comment by oharaandrew314** [comment]
@apemanzilla, did [this](https://drive.google.com/open?id=0ByGq5aXm4AHQYjNlUGZfV2oyZDA&authuser=0) solve the problem?

**Comment by apemanzilla** [comment]
Yup, thanks
