### ISSUE TITLE
BobPalmer mods seem to all activate together

### ISSUE THREAD

**Issue by cgruber** [oharaandrew314/TinkerTime#214]
... when I clicked on Karbonite, I ended up with K, K+, and MKS all activating together.  Several other examples of this - not just Bob Palmer's stuff.

**Comment by oharaandrew314** [comment]
What version/branch are you using?

**Comment by cgruber** [comment]
master as of commit ref 47cb93df05c9ec498a074a6b898598d2b4a077ca (update readme for new migration consequences)

**Comment by oharaandrew314** [comment]
I have another PR in the pipeline which contains the fix for #215, and changes the way mods are detected as being enabled.  RC3 available on PR #213, might fix this.

**Comment by cgruber** [comment]
Trying it out.
