### ISSUE TITLE
Module list just disappears

### ISSUE THREAD

**Issue by cgruber** [oharaandrew314/TinkerTime#215]
A weird regression seems to be in 1.3 (built from head just after the 1.3 commit that updates the readme), whereby when I activate some mods (no clear indication which ones, or what pattern this happens), the module list on the left just empties.  The mods are still there - if I quit and start the app again, they're there, including the one just activated (which is now active).

**Comment by oharaandrew314** [comment]
Don't worry, I have a fix in the pipeline for this.

**Comment by cgruber** [comment]
Ah - ok.  I'll just poke around for now.

**Comment by oharaandrew314** [comment]
I wasn't updating the list on the EDT (although I wasn't earlier, so I'm not sure how it was hidden).

**Comment by cgruber** [comment]
Curious.  Glad you have a fix.
