### ISSUE TITLE
Rename TinkerTime?

### ISSUE THREAD

**Issue by oharaandrew314** [oharaandrew314/TinkerTime#217]
@apemanzilla and @cgruber, you have been active here recently, so I would like your opinion on this.

I've been considering renaming TinkerTime for a while.  It sounds pretty silly in my opinion, reminding me of the Tinkerbell character.

I wanted the name to have something to do with engineering or tweaking.  TinkerTime has something to do with tweaking, and was inspired from the "tinker time" allotted in the old junkyard wars show before the machines are tested.

Ideally, I would like the new name to have the word "kerbal", has something to do with engineering or tweaking, be catchy, and have a good acronym.  Maybe something that pushes the fact that (as far as I know) it's the only mod manager to automatically manage updating from 3 possible mod sources (4 if you include Jenkins).  I want a good name so that I can really push the advertising for the next 2.0 release.

Any ideas?  Or do you like the current name?

Ideas:
- Kerbal Dukt Tape
- Kerbal Mod Glue
- Kerbal Mod Struts
- Moar Struts

Update:
[KSP Forums Poll](http://forum.kerbalspaceprogram.com/threads/114660-Poll-Rename-Tinker-Time-Mod-Manager)

**Comment by cgruber** [comment]
I like Kerbal Dukt Tape personally.  KDT.  Totally has my vote.  I dont' mind the current name, but KDT is way awesomer.

**Comment by apemanzilla** [comment]
I agree with that. Moar Struts just sounds like a mod. The others don't have the same ring.

**Comment by oharaandrew314** [comment]
@apemanzilla, do you think that I should change the name to that?  Or do you like TinkerTime, as well?

**Comment by apemanzilla** [comment]
I don't really mind either name, they're both fine in my opinion.

**Comment by oharaandrew314** [comment]
Looks like I need to find some more opinions, then!  Maybe a poll in the KSP forums after I release 1.3

**Comment by oharaandrew314** [comment]
At least TinkerTime isn't as terrible a name as I feared it was :P

**Comment by cgruber** [comment]
:)

**Comment by oharaandrew314** [comment]
I'll consider this again later.
