### ISSUE TITLE
Odd NPE when launching game

### ISSUE THREAD

**Issue by apemanzilla** [oharaandrew314/TinkerTime#229]
When attempting to launch KSP, I get an empty error dialog box:
![Image](http://i.imgur.com/fbYUVua.png)
No error appears in the console, just this dialog box. Fresh install of KSP with no mods yet.

**Comment by oharaandrew314** [comment]
It looks like you're building off of branch v2.0.  I'll look into this
regression.

**Comment by apemanzilla** [comment]
Yep, wanted to test it out and start work on some of the issues I made a while ago. Want to get back into coding while I'm on break.

**Comment by oharaandrew314** [comment]
Ok.  What issues do you want to work on?  Do you need me to fix that right
now?  Or should it not get in the way?

**Comment by apemanzilla** [comment]
On a side note, the circular loading bars on the mod list items look beautiful!

**Comment by oharaandrew314** [comment]
I'm glad you like them!  I'll get rid of the lower panel once I get the
installation of new mods appearing in the list.  Kind of like how new apps
are installed on iOS.

**Comment by apemanzilla** [comment]
I was going to start on #178 and #153. I can still work on #153 with this, but for #178 I need to be able to launch the game.

**Comment by oharaandrew314** [comment]
Yeah, feel free to do #178, because I don't really care about it enough to
do it.  I'm kind of in bed right now, but I could fix the bug really quick
for you of you can't figure it out.

You should run your plan by me for #153 before you implement it, so I can
give feedback and tips.  I'm also considering getting CKAN metadata, so I'm
not sure how I want the two implemented.

**Comment by apemanzilla** [comment]
Alright. For now I'm going to bed, but tomorrow I'll work on these more.

**Comment by oharaandrew314** [comment]
OK.  I have my last exam tomorrow, but maybe I'll get the bug fixed for you
before you get back to it.

**Comment by oharaandrew314** [comment]
Should be fixed.  Can you let me know if it works now?

**Comment by apemanzilla** [comment]
Yep, fixed. All is good. Thanks!
