### ISSUE TITLE
Numeric identifier MUST NOT contain leading zeroes

### ISSUE THREAD

**Issue by kbytesys** [oharaandrew314/TinkerTime#233]
I'm unable to install this module

https://kerbalstuff.com/mod/172

The zip file have leading zeroes in the name, btw you have manage that.

Regards

**Comment by Krahazik** [comment]
I have encountered this error with other mods as well.
At the moment every time I start the program I get that error message and I'm not sure which mod its having a problem with.

**Comment by oharaandrew314** [comment]
Duplicate of #221.  Was already fixed, but pending release.  See https://github.com/oharaandrew314/TinkerTime/releases/tag/v1.4.1
