### ISSUE TITLE
Export all modules

### ISSUE THREAD

**Issue by kbytesys** [oharaandrew314/TinkerTime#234]
Only enabled modules can be exported at the moment.

It will be nice if we could export all modules.

**Comment by oharaandrew314** [comment]
As a workaround, the file would be equivalent to the mods file, stored in
<KSP Directory>/TinkerTime/TinkerTime-mods.json

**Comment by oharaandrew314** [comment]
This will be related to #224.  Instead of exporting the old-style JSON data, a newline-delimited list of URLs will be exported, just like the expected import format.

**Comment by oharaandrew314** [comment]
Done in 9f9487f
