### ISSUE TITLE
Add ability to import mods from a text file

### ISSUE THREAD

**Issue by oharaandrew314** [oharaandrew314/TinkerTime#238]
Have TT read a list of URLs in a text file, newline-seperated.  It should then add them.

**Comment by oharaandrew314** [comment]
There should also be an option to import the legacy json format.

**Comment by apemanzilla** [comment]
Why make it a separate option - try to parse it as a list of URLs, if that fails, try it as JSON.

**Comment by oharaandrew314** [comment]
Yeah, that would probably be best.
