### ISSUE TITLE
Tinker Time ignores -force-opengl launch argument

### ISSUE THREAD

**Issue by rasputine** [oharaandrew314/TinkerTime#241]
When I put '-force-opengl' into the 'KSP Launch Arguments' option text box, hit OK and then launch KSP through Tinker Time, the game launches without forcing opengl. The launch option works as expected through steam or modified shortcuts.

Using v1.4.2

**Comment by oharaandrew314** [comment]
Thanks for bringing this to my attention.  I will try to release a fix for this in the upcoming maintenance release.

**Comment by oharaandrew314** [comment]
How does one even tell whether the game is running OpenGL or not?

**Comment by oharaandrew314** [comment]
Fixed.  Silly mistake.
