### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by oharaandrew314** [oharaandrew314/TinkerTime#244]
Thanks to the added overhead of the database migration and ORM tasks, TinkerTime takes longer to load than before (but this may not be so bad when launching from a JAR with no console output).

Add a Splash Screen to show the user that the application is loading.  See the tutorial [here](https://docs.oracle.com/javase/tutorial/uiswing/misc/splashscreen.html).

The Splash Screen could optionally have a progress bar or steps counter which goes through these steps once the VM starts:
1. Migrating Database Version
2. Initializing Database ORM
3. Starting TinkerTime

**Comment by apemanzilla** [comment]
Alternatively, you can also use a borderless, always on top JFrame, which will give you more flexibility.

**Comment by oharaandrew314** [comment]
Yes, I'm sure it will. This spash screen is intriguing, though, with how it
is displayed even before the VM starts. It would be nice to get some
feedback as soon as the JAR is launched.

**Comment by oharaandrew314** [comment]
![splash](https://cloud.githubusercontent.com/assets/894152/8490737/df28154e-20fb-11e5-932c-9b310a835772.png)

Lameness scale from 1 to awesome?
