### ISSUE TITLE
preselection upon delete

### ISSUE THREAD

**Issue by maxix** [oharaandrew314/TinkerTime#265]
Hi Andrew,

when i select a mod with right clic, then delete it, then right clic the next mod, then delete it, the next mod isn't deleted.

Tinker Time 2.0.0 on Linux.

Thx

**Comment by apemanzilla** [comment]
This is caused by the selected item visual not matching the actual selected item (which doesn't exist any more)

**Comment by oharaandrew314** [comment]
I agree.  Likely the forced selection change doesn't fire the appropriate event to the ModManager.

**Comment by maxix** [comment]
Unfortunately, I can still reproduce this behavior with 2.0.1 on Linux with OpenJDK . Do you need any material? Tough it's not a critical bug...
